version: '3'

services:
  account_db:
    image: postgres:16-alpine
    ports:
      -  "5431:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

#  api_server:
#    build:
#        context: .
#    ports:
#      - "8081:8081"
#    depends_on:
#      - account_db
#    volumes:
#      - ./app:/app