name: CI test

on:
  push:


jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install golang-migrate for ubuntu
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/
          which migrate

      - name: Migrate DB
        run: make dcu && make migrateup && make test
