name: CI test

on:
  push:


jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      account_db:
        image: postgres:16-alpine
        ports:
          - "5431:5432"
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install golang-migrate for ubuntu
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/
          which migrate

      - name: Migrate DB
        run: make migrateup

      - name: Test
        run: make test
